### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by Steven-Zhl** [vuepy/vuepy#2]
## Problem Description

- I encountered the following problem when I created a new project by executing `python -m vuepy create` according to the [Quick Start](https://www.vuepy.org/guide/quick-start.html)

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\Steven\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vuepy\__init__.py", line 21, in <module>
    from vuepy.runtime.core.api_create_app import App
  File "C:\Users\Steven\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vuepy\runtime\core\api_create_app.py", line 25, in <module>
    @dataclasses.dataclass
     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'vuepy.compiler_core.options.CompilerOptions'> for field compilerOptions is not allowed: use default_factory
```

- It looks like the `api_create_app.py` is not executing as expected.

## System

- OS: Windows 11 23H2
- Python: Python 3.12.5 (installed via Microsoft Store)
- org.vuepy.core: 0.1.5

**Comment by leilux** [comment]
Fixed in version 0.1.6a1
```bash
pip install org.vuepy.core==0.1.6a1
```
